### ISSUE TITLE
Suggestion: Recognize time zone abbreviations in !time and !meet

### ISSUE THREAD

**Issue by Timst** [Djidiouf/bbot#35]
For instance:

!time UTC
!time CET
!meet 19:00 CEST

Maybe even:

!time UTC+1

**Comment by Djidiouf** [comment]
!time UTC and !time CET is already in place through the pytz library.

for !meet CEST 19:00 it doesn't work for an unknown reason, the CEST timezone doesn't work. however, you can ask for !meet UTC 19:00 for example

Thank you for the !time UTC+1, that's a good suggestion. I think that is something that I can set for every time zone as well.

**Comment by Djidiouf** [comment]
Fixed in the develop branch
