### ISSUE TITLE
Typo in modules/steam.py "played to" -> "played"

### ISSUE THREAD

**Issue by ThomasGirard** [Djidiouf/bbot#44]
In modules/steam.py

modules.connection.send_message("In the last 2 weeks %s has played to:" % (player_name))
Should be 
modules.connection.send_message("In the last 2 weeks %s has played:" % (player_name))

**Comment by Djidiouf** [comment]
I've forgot to close the issue several months ago but it has been fixed, thanks!
Your feedback is important to us.
