### ISSUE TITLE
Currencies: only auto-convert when the currency code is in uppercase

### ISSUE THREAD

**Issue by Timst** [Djidiouf/bbot#55]
To avoid the "1 lvl" and similar issue. Having to write the currency code in upper case doesn't take much effort, is what we usually do anyway, and is useful if you want to avoid triggering the bot for some reason.

**Comment by Djidiouf** [comment]
Thanks for this feature request!

I can't say I find this solution appealing though.

The purpose of the money-inline function is to be handy and to catch occurrences where people speak about money. Having to put in all caps the currency makes it self-conscious and though, it goes against the purpose of this function.
In addition, it will not really solve your issue. 1 LVL would still be caught up by the bot.

I set-up a blacklist in the config file for currencies not to be processed by the bot. I believe this solution to be appropriate, specially as every bbot admin can configure it to their needs.
