### ISSUE TITLE
Currencies: Currency symbol followed by , or . leads to a conversion

### ISSUE THREAD

**Issue by Timst** [Djidiouf/bbot#56]
Timst-web
$, 

Bretton_Woods
0.00 USD = 0.00 AUD | 0.00 EUR | 0.00 GBP | 0.00 NOK 

Timst-web
$. 

Bretton_Woods
0.00 USD = 0.00 AUD | 0.00 EUR | 0.00 GBP | 0.00 NOK 

Timst-web
€. 

Bretton_Woods
0.00 EUR = 0.00 AUD | 0.00 GBP | 0.00 NOK

**Comment by Djidiouf** [comment]
Thanks

The origin of this is because the bot takes care of notation like $.50

FIXED in develop branch
