### ISSUE TITLE
Calc: trim trailing zeroes

### ISSUE THREAD

**Issue by Timst** [Djidiouf/bbot#57]
> arrg_
> !calc 2560*2 
> 
> Bretton_Woods
> 2560*2 = 5120.000000 

This should be "5120" (and 2560.25 should be 5120.5 etc). I don't know python but in other languages this can be achieved by casting the result to a string and using some trimming function to remove the "0"s at the end.

**Comment by Djidiouf** [comment]
Thanks!

FIXED in develop branch
